apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-controller
  template:
    metadata:
      labels:
        app: agent-controller
    spec:
      containers:
        - name: agent-controller
          image: iahmedsabry/agent-controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: LLM_API_URL
              value: "https://labs.pluralsight.com/labs-ai-proxy/"

            - name: LLM_API_KEY
              value: "6753961d-9bf0-4fd2-ac06-f6604833c5af"