apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: default

data:
  default.conf: |
    server {
      listen 80;

      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      # Handle /aiops requests
      location /aiops {

        # Return index.html for the UI
        try_files $uri $uri/ /index.html;
      }
    }