apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app  # Name of this Argo CD app
  namespace: argocd  # Argo CD runs here
spec:
  project: default

  source:
    repoURL: https://github.com/iahmedsabry/ai-ops-platform-gitops.git
    targetRevision: HEAD
    path: manifests/argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # where resources will be created

  syncPolicy:
    automated:
      prune: true       # remove old resources
      selfHeal: true    # fix drift automatically