---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-secret
  namespace: default
spec:
  encryptedData:
    GEMINI_API_KEY: AgBE5l1Z6Tnb3WeVQPj2A/tUimyA46ovLkKuEkzCeYkBNsmoxzr29ua2z4rZT6FSuW0SO1/Q39DsR9mpPsIrfgnkaZ8Lxt1dyaL1QaC2mIGaiQZMN0rQcVnwff26+CbDtIe+PZl1t7foFlwuX1BTWtXl65uT7ppz8RvL8TSXy6vHsh/F9g136Q9przYcQQoMWOmH5Xv2+i/lo8elAz7Co0f2fKD35BcBle4o+2DqmxN0RJnpzCvkass/05s6fgyvmhLP6cQrzkfarPEVblcT2hw6ujt060bM7O26r05Tuo5vUOt8iB1duAqEltxDKe+cjexNhJYuKsVqmCkW25QoCA/l1c+MHIuPWMr5JNvnesBdZVDQxUcQQG5C4fKzsitFoneYuFcLb6x8K1OuwZVygl1csoBwwJeJp52Y2U+oj9H4xGe/Eh6br4TT7dV1M1yGDIXQIHdWQoRT9OklDnWeBDUN5y/cBvh4z253eY/WqP2ScfeaRUSnZ7RLoAVP43q1FsL/uW61dSbhKXjo4AY7AIBq0stCz7XMRMxlMUFK0ZepT31O9u4D7pSRBUAdHJrWaGOpFltHwGe9ZqiaOYu4uzOw69rbUDi7xFXYv856e1mTTeLWDiwYg2B7WVq91o8y13LrLwjuzmx/RFC2J95RdAuyTenguJ7K2D3KJ5rW5r9Mo54gOkrKCUTKxCZX7bN8TfP3SH4VBU2ghLpAn6Pj8KD46XBnKQU/Ywv/sWIqxMr09P1KE5eQ5zo=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-secret
      namespace: default
    type: Opaque
