---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgBJVgQUKcTGKp8QjYip/QrYovODV8cPrJw2mhTJeRcCDAuS2epniLYm5bkX2fEYYaVhoBWaJbnOjaF0E0oC2WXs8758WZh7c9myiF/6zgHIFUb5osvBwIH7zDZ4yr3AaRHM1OiCMpHqMaeKJ795lczVF0VMIl3FtUaf2AjZPq59ML7H5Vlt0gPLKLlohYNJLGFYwUcy33H0RLfV0Rponnw1k1DeZUmEpVB6pFThHF4yL/ZNHr77DEkFK6RwGFNjnKbTJ7eQkdtadkeX1AoLf7KmvB2ix54HW2WDkQtVyC4WDtsl36DvA0oeSed6daBiGP514ie70M2EtnJEsL83WxUQFbCRsY9rs/Q5rUCbq8VmOxahUAmVVI3SL75Cb8OZkFxPz0NpL1UH482wXPEboTy9hPzcVmxWWR+i6Z9bav1/NX8FQ+SfSeWh/ysQ320giFR4dv+OFt7JDrWEKkQDs52zkquJjPpp32Y3eq9yu9YCvo7bswiER124xnDS24tOR4os/ZKbJMsS2aubMB0oiGLklp4Lv0jLNtc3IcAOo74RfGRok7VXXL3s5aEjlwW9df/i1t2PMKmLzzLmupMb8Ynj49Gl3KNsTMU9heOCxLzneMMhCMdl4YXX9xoN6uv67vGx8DDLaKmlIDuyKLi2aMoY5f64gP6K3SHRt0pDLQJjj1EOr17N9otRSHprtByfTpGf7tCRAExie9EYVPb11A4=
    jenkins-admin-user: AgANingIZxpUS5R0qj164XU+EYieSXwy76UX/U2pgXDd9Pu3l3mYGbJng5as4O4S1Omv/NecL1hIp3hGNgLo4PiCLJEYB82ZBPhd5AhG74E1HrAUgQMc9LXPVPVeoM/09frnDjgLDUJBv0KhtCD/YSEK7Y7+8oLbF19ZqP/VS9CfQc1FY7cA2I2hj89nKuwz5T/TFnNqX0J0I2ZRDUvAXYamJUQ4mGAQc6ozRYbUyEgLAaLVpdP3u+VUeqX/1m7bKrFzyHUgE+zjp3tK65DpX0oCSxW6w+isEiK1DUxhJAUrfPtR4yiC60hf1rNTOdT1O32/YYOIdPTsCNlRGrDNFyhJ8EjRBp6/UrNWUqQfxGTw84o2YTzRszlnrvQ+57Iob+6Jxy5GfCEiKdqU6wr660hLQivLCKjw5A+EFN3k94ncvpdMxhVT+jQeu3mDM/6CWAGk2dnfvL05PGShW8PODmhL/jTgywzKF/+MdBT70q4CDzj5LhY8z8EYrLWckgG+YZWw+Qa/MRwdtiSOsC3P7jrta1+nlEkKbKcZk3cT/HTDOU/NJJZWejViGWqLTINP2HUtuQKpx7+79F/ftfxBE0KfuFQwK0zgy47tHGjDq/xvNr+UpCF6lx8K2TLHEcSNvlWoc5qaT2wETQ4h4dLAKr+cHRxq651XvU0zkLnq8v4L5EHjLgRaGCG2YhVJgb+2CVx3ojG0fA==
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-admin-secret
      namespace: jenkins
    type: Opaque
