---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: llm-secret
  namespace: ai-ops
spec:
  encryptedData:
    LLM_API_KEY: AgBVo5NkNMD6BaWLTiyYGJZiPe1xXTdgUoqNGV2VgIdaxehVAeRnASlBsRAznwJDyhNG/iwd4LrmdO/SGdrpszjMV33CsNJuainXO0rInXgT5Q9UercmB4VfUUZ2liz/+EYdFpLUNFpLzhkBSHgabP36Lx+pR3BdiQZsQYHJY61qVp44S+rbb5juaeX9LtZ0/74Fr37vVn/xHoYaTC3vtEMfj9HeuQZ//JxmBh6fGzS2w2LG5Dw15K+sUCrPcTghrMy0m7Hx6Hi7es3du9vxr0zKHaHpI/cVhyKnd09jelh3VFl444njQfgI4cvgWKUAAHQjVUAnOs7+m5fXagsXoqAqY77nzHwM0O9z9+Ydaycp/VOJyncFKoVBW/mSUko2NtjMakHqvDXzbobPZq7lWZpauN6o57mGcSAUb+DnGVropSqhUmETy8Z2wfuUEFJK4AlONfrhdqZyAwr1u7ft1TNne7d1rXXJLpfJZ8uESAcVgRq2P5M8NepEqfCYvs166D3Or4u4vk9Y0L9Hh095FhW1hOkim+72SEk1ZZXHYhWxgryUVkKxPbTgilDjiezDIHhycKMwaw/2KhUIFvuUv4Q31XncvsdNIp+sdHRpU2iv8Bdr/T/CYccoZXdN7TWRlYAWYz0d9c2mix+VHzrXtSiv8cnWQ/X2vqlISWqQ5lcR2kElu+N287XTiglgbpdh2zOjmyr6QzMm4bkMsBwC6sDIv3xwoi1/kttqcUrch3LWx50ykf4ye7M=
  template:
    metadata:
      creationTimestamp: null
      name: llm-secret
      namespace: ai-ops
    type: Opaque