---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: copilot-auth-secret
  namespace: ai-ops
spec:
  encryptedData:
    COPILOT_PAT: AgAXZrw4cWzpk7hJDT+259Qgbc90PG5eVUrUkj9Bw2nx8xO+i+3AHjw7UoWI9ZPOoBq2pRpMZ5HCTYtmLP6g1OCoZ58q9BxPD1plf01bYDHldxPJItvC0EZPsX0P5LXF86IN3VE2V80tNn2xMNxmZt/Az6KUZV9p7ax4Z6X2BRdZbigyCry8E4UcQuL3LldbIETOz9RH40F81LSfYBJo2aQzw1BU3txHi9Htb0kIPdDRm57O9/lfo/7M4Exh7Efyv+PQSJAYmQ3agZ7LfL5eBLFoVkMcjSiup+LQ8zu79g47FMRVtAs9jOTAFuw20CkLMZyx0hMFGft9B9Xl1hMdxYUrQatNj9BM2255z13oT+vOjSxjaAjG66C5zAQnDczjwLPrujILUUxYlC3L0v5/YqIoWMubc9nSZ73nfiCWX9kTUX79oCUrpqZdMuM0a5WPZujgvWX0/kopzutIjP0TlBQToT/zp+ZorFjsmoAwpGTBamzXBNisF9gXLgNg2gvBEnnOb5493z/6OYSy7pHfOX/aT6esxaPHpsNM7LBAiuq2wEL29lDNc/jGzkA4QrkW1BbUOsGeBAG2rL1jyMNYqwz71YQBWp+6VfREb3njp+G9lGt7gpsDMk1JC1RU6kpiMLI5ssXyuYP1lAn4kQcA3RJBrN6g3n7ajQG+NXuJnLNyYPMVsSaSHy0hDLAR03OdfOAGwbvJjjT3zQQ8RHYtWMHM9JasJ6v9hc8SufjX+UYd4iGB8h/c0Qy8grAxHV3nKkwTWped2F5WCCAJ92sMbHXDbCzJjLbFHzzVV2K+fygTTJyHVuq4RHeUyt2tygc=
  template:
    metadata:
      creationTimestamp: null
      name: copilot-auth-secret
      namespace: ai-ops
    type: Opaque
