# PER-ENVIRONMENT: encrypted with a specific cluster's Sealed Secrets cert — regenerate with `kubeseal` for each EKS cluster.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-secret
  namespace: ai-ops
spec:
  encryptedData:
    GEMINI_API_KEY: AgCff/ofbJwQ3hNHM/q7wNU4lBh8Qej5Fyqfbxrpwqfq58DXoQkiZ0PREirBaTwqnZ//2uRAZDH/HQKi57ivKCva/iInSGRic5+m6rc4eg1oDpcbMxZ3omBgGnO+gcjrBg3bh+d9o3/g6wuinxqjg8n4381YnCJGFzTgaIy9Gtf4fXrqdVvMayRmySQPQ40rHiHsyC8sPcAjatF6fwv13IR6sX4q1PqZma/ryqLxCMT1jABujTM/9s2KZnmIKuyg/K0SrSQfmjM3L2Ge8sEBDDQHMgC8hkBd5lAFIV4g9xHFRcmUj8TdG+9Nqs8YvgKyDA279nBgMUz9Iaw4VTjmFUDm7AvHY80IXAxvlU1hTP0u4Q4vkXCXgOCawPzj+9ybDQNz8mHEq67bbwwWGBJP/uhQuINVABDd9jTeevsZyvlzut9ir+zBrLyERgwHtBZcnOrgcBFga+7s/XiIAaHfJ6ioa5ltyF9d9G2pJhBDIuFmo+VvfjL7sRPh1TqTr+fFXjKJ2FyygEP4GLah89BLEJWpIIbsp2FJ6JpJISkx5uO1eUGg6rOgboV3RFFiMjXHO25kurfRMGNHQNzriAGjH6PUNdqQoxp8MPKPCtw1qH1iNFpdfzOwIuF1mQyRMvsVbeyomtBv3B1Brz4nBRggj9ptfNfpkWWR4VHtQktP435+SRmYISZnM5LjMRAdVyEMLtW2ZlehUZGudJmMXI3pNLBj3ZwV7dyFTLdviJNEmndUThuwivjMK3o=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-secret
      namespace: ai-ops
    type: Opaque
