---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: copilot-auth-secret
  namespace: ai-ops
spec:
  encryptedData:
    COPILOT_PAT: AgBKd/pw6yULN5hr45WRIzNH8tco1zOG/gIrxqNWxrbsKgcL1KriyMnDWCgSWN6cmg4NKyAzhkTEwAMVlvll8gZMxSTsawyo0/VzgaDhFmE/VQanbxex45o3ELjBevzXbPW6nY0iXvjZDCbyH8OB1lh6SFZkWhx7wnbVUk84ueDD6xFap8yZJ6LzZbouiUPMc7iuZs9GlPwpc3+cBMaU+01VuqoVHCR0A88xwxqhY2lhPT0YK4lKHPg3KgADox8oUbT6pEdLwkos/JaeGnP4qXKTs7/nITZzR5hO2vEYAUwsPbnJIe12clwFCIb98jH1gtBn8k4ibQKyHctQPAMZ0MijLFy7LGRTEF50P+zbGppRxEg/TberwwkhPYhui/mvQVCjWdHMm4pxBTaxomuXrxmD/jaVJqz17yfc+XtKzDAmEH7Cb7MNMYzoIxqVPfl/rbXN2Pw+1I6Xeubpvc2d3JnTOPThhgoSzlPcSahqQZ2C28+q3q+kKLqD+wb+SAFBWthPEU14dLgEKQrhtZLLUbnXyi/rwOOthnHh/dOCiYGT8F0SAjkbIESiwAq0vuAf90fRVBevtZgseJs2jQvED2TPJt47jWwfqnYNsiPv7bBy8VuMFCu1CldwK0VLA9KCfDDxix7k1ZRa2OKwFFuyCY141v3QB6urO2dU6gKxpICVG64yR1K83elfav6v7EwshVdHorHCS2G632ANY9QG99QqmPLuZE8oI1wSoPlYkZoysZEgZBHf05Lf+G3oum2+z6U/bqYOpe3j8OV+1TRBxBuwliqiH12IIeZxWxzPe2eDtgMjssJUeVju+fXdb4Q=
  template:
    metadata:
      creationTimestamp: null
      name: copilot-auth-secret
      namespace: ai-ops
    type: Opaque
