---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: llm-secret
  namespace: ai-ops
spec:
  encryptedData:
    LLM_API_KEY: AgByjv6NXKe14u3qDoxZgZFv1EpX59y+dZ9EEzIaabh/PsxRJw3PpGRlh81RsBBQY8O6RPvOewGr6ESwiinIrzW/MZkiiOmrwMjrFxkmxPNqBEwVnHeVDbC3+OGgOh1xwXIhrQM+S2+aUkKpyWvngMqFZUizkbAjQlX3XfkrQ/yZX1bPXeCNKU8r8G9CuGanaIAzwgZjjfERUUyXcWAtwp0K5m2BciSikSYR0dOepzDIK8nS2dOvugS9D3Y3Tt+dqBWqZ8BIDDHWvfo0slFTk1npZFOBn4wMIS0bemTjWsbe8IPjeiq1lqP3MgeirPsMBeCIaV2iTMTqeF/fyfG+x6ZKUpmFVk6/8J1YuOT/p3tgfQnu02XQrEEMlRG4BWfDBP2lylo7gVsSJZXH1WHrenls1psnXNPLVHenS3jMsTazKnrWI52ajyiq8Y12nyvpykZ9UJOTLLJ8nMdNwHrnYdHCe8b85LOnuDr/kGA+YFtVPuR9RTwGgEXeTRJ7UmGzLa8WE2uVlqbYxBN19xGyCluWrJ/jG7YuHBnl/WJ1MgD5laqMxxK8JvmkyUPE6fHAmaIVZerNPt8Y9NF6+JEZnnT6iJaRAxGcJzEHtDxAD2UNlqlr4v6HG6HgrFCpmCd+D4RXKW9jfPKPoiBLB7XTy+gI1tEliOoQtTIDtgMrBxbTO8G58fMc+1nVS27GeYNgUgmPIa+483LfgReQmL0ViYtS95UwCg82NqrYIT/OwuUrVoRzK1b0Qf0=
  template:
    metadata:
      creationTimestamp: null
      name: llm-secret
      namespace: ai-ops
    type: Opaque
