# PER-ENVIRONMENT: encrypted with a specific cluster's Sealed Secrets cert — regenerate with `kubeseal` for each EKS cluster.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-secret
  namespace: ai-ops
spec:
  encryptedData:
    GEMINI_API_KEY: AgBF2hE67gkz5zBGwm4ZhpI6EL+iGPEc20P083UrDypyUCRMZ19Nq5vmafGHr56H1fm86cnzNu1vcTMazrpgLKp1IDaD7zw1oZplQ0l6gnr2RxLv4njNbSUF9i5mQYR+8zcAvA3t3Tas+Sa5lAC4rfDG4rQhxVumZClr7z9optqs/Jlp4MBfb/k+O2FyZb+vA41pRukddW9/qK6nX274Oix0zBpmgde21jmkckDsZ3b8JGQXExYA2NEtsiP206QD9W3GUAmagZeE1udcvQgPlm5kg1eFR6XiFEG7OHQIaWFMBvA8RISgk1mcN14dvVbUX11KoVG4VhJfBJ+sIIpydwIcnXylEiIhNv3ix3vQdtlPsfeBiMBUgkdp6VXkmO1ITqwdgbcWIchL48H99RwUDRRvABY36IUX58jy7r4HyJZpUeoRmbEKevLHszX6MXfzkqyMhBB3wFoLvnFSbJ8oamZO8Orp+UoCvU+uPVdLc/aEpcviPEm4Cp1Dx/o2p7QDIYYX4v28XeDxMnV2ca/Y5LlEXjfVJpMMTcQ1bsVhYGhVau5LGR/O+i7aiFbYkxwJea/O4XWPnW4ILLqADgTQD4sVdnHg6GLO+ExgT2oXA82eR1r9AgfmyweG6g4EfPZBTPM0Q8MDHyXXdqSiCPVPvekUedFL/dTFEgd9iVW6GEWPlJQoUxsYQkiAAuBZyp+GIWopnrcmnKPAsd5aPG3TJOwShiae2yPmcBeasETeenI9a8oyfYPxm4A=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-secret
      namespace: ai-ops
    type: Opaque
