---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: llm-secret
  namespace: ai-ops
spec:
  encryptedData:
    LLM_API_KEY: AgB89aP2u4Fa0xdV9T+SPHDX7GGt8VJVPT2v+3NULu/Rz7tqJ1MZ6/mp6hlv38FMirFLEdbcBMmsVRH9zUMzahfrUP96VamyzoNAFB1AA9decDwa5oCOba/0LZjqocTq8tp2ZyDoVVJNWDICkZrCHwCNEu9jcr3kYGCTFKPL4lGvDUuzra7ifk9lI4slWPU2YGoukibXcXlh/KOzGWUHm5C49gTjyiTk2X6Bb5nxbSA6pJaD2kFhbjya0mqkwlLX2OYqXJujlqNjqEqES51bXS1GpIVP9yfjksTcI8XWeb7HTWdNPj6ZD0UjZtCRxLTdAKJGh5UCWLiUyVKiTAi3ne3jr86RJFdK+jrRmgKe53tcLBeWaexk/z3A/Csej1qRmdXs8wiYr39ggPgY+K1tSqYgewhNHJOP0Po42p2TByVC3CAXaq2YjauCXAC8bLN3veYN1i56AEw19X1mTLZkXSi/TkTwqNFUunYnxKFf0i6J/T3HpcqKWiJ/scBmSjpqXa//OELVbqDcpbfdRNfM6wiEyeJOTmOfqEXOD66u5AnBi+3j6aj8ZZ5NLAKemujQdfHUvXK74394OWHGTP5BAPJtmXkn3TKMXlAUu1bF2PyH0hJSEuwbQaV1cJffnjflzQE4OWGROP7kuB3FkIqjK7Bhj3VEn+pPeKpdYp4/GYoNxuApSC8kVT8UXDwSfiWaxWNDHbIbPrBW4AZs6layQFSwuay1KYj7kvn8vTkvKFtbWuzlRkx7DmSDhIUDIapQKK3JtqOKadFT1vmcFI6BUNsp//lbqHc1XyGYX7xGX0iM3F0FOkzYh8XsxHTD0LA=
  template:
    metadata:
      creationTimestamp: null
      name: llm-secret
      namespace: ai-ops
    type: Opaque
